name: Assets Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "apps/assets/**"
      - ".github/workflows/assets.yml"

jobs:
  deploy:
    name: Deploy Assets
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install lftp
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          echo "NEEDRESTART_MODE=a" | sudo tee -a /etc/needrestart/needrestart.conf
          sudo apt-get clean
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends lftp
        timeout-minutes: 10

      - name: 📂 FTP Sync Assets
        run: |
          lftp -e "
            set ftp:ssl-allow no;
            open ${{ secrets.ASSETS_FTP_SERVER }};
            user ${{ secrets.ASSETS_FTP_USERNAME }} ${{ secrets.ASSETS_FTP_PASSWORD }};
            mirror -R --verbose --parallel=10 --use-cache --exclude-glob=docs/** --exclude-glob=images/** --exclude-glob=.env ./apps/assets/ .
            bye
          "
