name: Assets Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "apps/assets/**"
      - ".github/workflows/assets.yml"

jobs:
  deploy:
    name: Deploy Assets
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 📂 FTP Sync Assets
        run: |
          sudo apt-get update && sudo apt-get install -y lftp
          lftp -e "
            set ftp:ssl-allow no;
            open ${{ secrets.ASSETS_FTP_SERVER }};
            user ${{ secrets.ASSETS_FTP_USERNAME }} ${{ secrets.ASSETS_FTP_PASSWORD }};
            mirror -R --verbose --parallel=10 --use-cache --exclude-glob=docs/** --exclude-glob=images/** --exclude-glob=.env ./apps/assets/ .
            bye
          "
