name: Test FTP Only

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Build & FTP Sync
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "20"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: ⬇️ Install dependencies
        run: pnpm install

      - name: 🛠️ Build Next.js application
        env:
          SANITY_DATASET: ${{ secrets.SANITY_DATASET }}
          SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}
        run: |
          cd apps/web
          pnpm run build

      - name: 📂 FTP Sync
        run: |
          sudo apt-get update && sudo apt-get install -y lftp
          lftp -e "
            set ftp:ssl-allow no;
            open ${{ secrets.STAGING_FTP_SERVER }};
            user ${{ secrets.STAGING_FTP_USERNAME }} ${{ secrets.STAGING_FTP_PASSWORD }};
            mirror -R --verbose --parallel=10 --use-cache --exclude-glob=docs/** --exclude-glob=images/** ./apps/web/out/ .
            bye
          "
