name: Web Staging Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
      - "apps/web/**"
      - "packages/**"
      - ".github/workflows/web-deploy.yml"
      - ".github/workflows/web-staging.yml"

jobs:
  deploy:
    uses: ./.github/workflows/web-deploy.yml
    secrets:
      SANITY_DATASET: ${{ secrets.SANITY_DATASET }}
      SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}
      FTP_SERVER: ${{ secrets.STAGING_FTP_SERVER }}
      FTP_USERNAME: ${{ secrets.STAGING_FTP_USERNAME }}
      FTP_PASSWORD: ${{ secrets.STAGING_FTP_PASSWORD }}
