name: Web Production Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "apps/web/**"
      - "packages/**"
      - ".github/workflows/web-deploy.yml"
      - ".github/workflows/web-production.yml"

jobs:
  deploy:
    uses: ./.github/workflows/web-deploy.yml
    with:
      deploy_path: public_html
    secrets:
      SANITY_DATASET: ${{ secrets.SANITY_DATASET }}
      SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}
      FTP_SERVER: ${{ secrets.FTP_SERVER }}
      FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
      FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
