name: Web Reusable Deploy Workflow

on:
  workflow_call:
    inputs:
      deploy_path:
        required: true
        type: string
        description: "The path to deploy to (e.g., public_html or beta)"
    secrets:
      SANITY_DATASET:
        required: true
      SANITY_PROJECT_ID:
        required: true
      FTP_SERVER:
        required: true
      FTP_USERNAME:
        required: true
      FTP_PASSWORD:
        required: true

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "20"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: ⬇️ Install dependencies
        run: pnpm install

      - name: 🛠️ Build Next.js application
        env:
          SANITY_DATASET: ${{ secrets.SANITY_DATASET }}
          SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}
        run: |
          cd apps/web
          pnpm run build

      - name: Install lftp
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          echo "NEEDRESTART_MODE=a" | sudo tee -a /etc/needrestart/needrestart.conf
          sudo apt-get clean
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends lftp
        timeout-minutes: 10

      - name: 📂 FTP Sync
        run: |
          lftp -e "
            set ftp:ssl-allow no;
            open ${{ secrets.FTP_SERVER }};
            user ${{ secrets.FTP_USERNAME }} ${{ secrets.FTP_PASSWORD }};
            mirror -R --verbose --parallel=10 --use-cache ./apps/web/out/ ${{ inputs.deploy_path }}
            bye
          "
